preferred_syntax = :scss
http_path = '/'
css_dir = 'public/stylesheets'
sass_dir = 'public/sass'
images_dir = 'public/images'
javascripts_dir = 'src/javascripts'
relative_assets = true
line_comments = true
# output_style = :compressed